spring.application.name=product_api
server.port=8081
# Configuraci\u00f3n de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar los comandos SQL en la consola para tu taller
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update